---
- hosts: ws ds
  become: yes
  gather_facts: 1
  tasks:
    - name: install nginx 
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family=="Debian"
      tags:
        - ngnix
    - name: install httpd on redhat
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat" 
    - name: start httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
    - name: create user donas
      user:
        name: donatien
        comment: donas kent
        shell: /bin/bash
    - name: create group 
      group:
        name: cloudteam
        state: present
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch 
      register: file_output
      tags:
        - cfil
        - f
        - g
    - name: create directory
      file: 
        path: /tmp/os
        state: directory
    - name: copy content to index  
      copy:
        dest: /var/www/html/index.html
        content: "<h1>This is created from Ansible server!<h1>"
    - name: read data
      debug: 
        var: file_output.diff.before.path
