---
- hosts: ws
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: instal packages
      yum:
        state: present
        name:
          - docker
          - wget
          - lsof
          - passwd
          - unzip 
          - java-11*

    - name: create directory
      file:
        path: /opt/qa/spg
        state: directory
        mode: '0755'

    - name: create directory
      file:
        path: /opt/qa/spg
        state: directory
        mode: '0755'

    - name: create log files
      file:
        path: /opt/qa/spg/spg.log
        state: touch

    - name: Start and enable Daemon
      systemd:
        name: docker
        state: started
        enabled: yes