---
- hosts: wind
  tasks:
    - name: create a directory or folder 
      win_file:
        path: C:\Users\Administrator\Desktop\donas
        state: directory 
    - name:
      win_get_url:
        dest: C:\Users\Administrator\Desktop\donas
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz

    - name: update package 
      win_updates:
        category_names: '*'
        reboot: true

